In [2]:
#import necessary libraries

import pandas as pd #pip install pandas
import numpy as np #pip install numpy
import pickle
# pip install -U scikit-learn 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv(r'C:\Users\maury\OneDrive\Desktop\task3\Stock.csv')
df[5:10]

Symbol      Open      High       Low       LTP    Chng  % Chng  \
5  BAJFINANCE  7,021.00  7,047.90  6,775.00  6,780.00 -345.80   -4.85   
6  BHARTIARTL       763       763     733.1    735.85  -29.30   -3.83   
7        BPCL    397.15     397.2       375     377.4  -22.70   -5.67   
8   BRITANNIA  3,560.00  3,635.10  3,533.95  3,566.60   -6.80   -0.19   
9       CIPLA       892    976.05    890.65       965   65.05    7.23   

   Volume (lacs) Turnover (crs.)     52w H     52w L  365 d % chng  \
5          16.89        1,161.63  8,050.00  4,362.00         44.57   
6         111.43          830.06     781.8    454.11         58.55   
7         100.23          383.54       503       357         -1.22   
8           3.73          133.23  4,153.00  3,317.30          0.30   
9         144.59        1,380.90  1,005.00     726.5         31.89   

   30 d % chng  
5       -13.69  
6         5.70  
7       -12.45  
8        -3.42  
9         6.34

In [4]:
df.describe()

Chng     % Chng  Volume (lacs)  365 d % chng  30 d % chng
count   50.000000  50.000000      50.000000     50.000000    50.000000
mean   -70.133000  -2.930200      71.266600     41.203000    -5.996800
std    163.203678   2.677007      93.462062     37.358646     6.322546
min   -770.500000  -7.480000       0.300000    -16.020000   -22.080000
25%    -66.775000  -4.527500      13.472500      9.375000    -9.665000
50%    -29.975000  -3.300000      30.750000     35.860000    -5.705000
75%     -7.812500  -1.932500      99.200000     65.942500    -2.222500
max    158.400000   7.230000     517.880000    167.950000     6.360000

In [5]:
df.columns

Index(['Symbol', 'Open', 'High', 'Low', 'LTP', 'Chng', '% Chng',
       'Volume (lacs)', 'Turnover (crs.)', '52w H', '52w L', '365 d % chng',
       '30 d % chng'],
      dtype='object')

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
len(df)

50

In [8]:
df.drop(columns=['High','Low','LTP','52w H','52w L','Chng'],inplace=True)

In [9]:
df.head(5)

Symbol       Open  % Chng  Volume (lacs) Turnover (crs.)  365 d % chng  \
0  ADANIPORTS        750   -6.22          72.20          532.63         79.22   
1  ASIANPAINT   3,101.00   -0.20          10.29          322.53         45.66   
2    AXISBANK        669   -2.78         102.53             684         10.19   
3  BAJAJ-AUTO   3,370.00   -1.67           3.42          114.59          9.30   
4  BAJAJFINSV  17,200.00   -3.94           3.42          576.79         91.38   

   30 d % chng  
0        -4.65  
1         5.66  
2       -21.49  
3       -12.05  
4        -9.10

In [11]:
type(df['Symbol'])

pandas.core.series.Series

In [12]:
d= {"Symbol":"Name","% Chng":"Percentage Change","Volume (lacs)":"Volumein Lakhs"}
df.rename(columns=d, inplace=True)

In [13]:
df.head(10)

Name       Open  Percentage Change  Volumein Lakhs Turnover (crs.)  \
0  ADANIPORTS        750              -6.22           72.20          532.63   
1  ASIANPAINT   3,101.00              -0.20           10.29          322.53   
2    AXISBANK        669              -2.78          102.53             684   
3  BAJAJ-AUTO   3,370.00              -1.67            3.42          114.59   
4  BAJAJFINSV  17,200.00              -3.94            3.42          576.79   
5  BAJFINANCE   7,021.00              -4.85           16.89        1,161.63   
6  BHARTIARTL        763              -3.83          111.43          830.06   
7        BPCL     397.15              -5.67          100.23          383.54   
8   BRITANNIA   3,560.00              -0.19            3.73          133.23   
9       CIPLA        892               7.23          144.59        1,380.90   

   365 d % chng  30 d % chng  
0         79.22        -4.65  
1         45.66         5.66  
2         10.19       -21.49  
3          9.30       -12.05  
4         91.38        -9.10  
5         44.57       -13.69  
6         58.55         5.70  
7         -1.22       -12.45  
8          0.30        -3.42  
9         31.89         6.34

In [14]:
df.isna().sum()

Name                 0
Open                 0
Percentage Change    0
Volumein Lakhs       0
Turnover (crs.)      0
365 d % chng         0
30 d % chng          0
dtype: int64

In [15]:
df.dropna(subset=["Open"])

Name       Open  Percentage Change  Volumein Lakhs Turnover (crs.)  \
0   ADANIPORTS        750              -6.22           72.20          532.63   
1   ASIANPAINT   3,101.00              -0.20           10.29          322.53   
2     AXISBANK        669              -2.78          102.53             684   
3   BAJAJ-AUTO   3,370.00              -1.67            3.42          114.59   
4   BAJAJFINSV  17,200.00              -3.94            3.42          576.79   
5   BAJFINANCE   7,021.00              -4.85           16.89        1,161.63   
6   BHARTIARTL        763              -3.83          111.43          830.06   
7         BPCL     397.15              -5.67          100.23          383.54   
8    BRITANNIA   3,560.00              -0.19            3.73          133.23   
9        CIPLA        892               7.23          144.59        1,380.90   
10   COALINDIA     157.75              -1.67          118.30           185.5   
11    DIVISLAB   4,770.00               2.92           15.71          775.37   
12     DRREDDY   4,580.00               3.45           10.72          508.97   
13   EICHERMOT   2,495.00              -3.16            5.55          136.56   
14      GRASIM   1,757.30              -4.58            7.48          127.84   
15     HCLTECH   1,120.00              -1.17           22.07          246.06   
16        HDFC   2,820.35              -4.28           33.53          927.88   
17    HDFCBANK   1,500.00              -2.39           93.12        1,394.10   
18    HDFCLIFE        685              -2.77           22.37           151.4   
19  HEROMOTOCO   2,580.00              -2.62            6.85          174.04   
20    HINDALCO      441.8              -6.57          148.26          631.93   
21  HINDUNILVR   2,344.00              -0.35           24.51          572.85   
22   ICICIBANK        739              -4.07          189.88        1,385.86   
23  INDUSINDBK        951              -6.19           67.46          622.74   
24        INFY   1,702.55              -1.91           44.94          764.67   
25         IOC      125.6              -3.58           77.25           94.57   
26         ITC      228.9              -3.33          270.27          610.54   
27    JSWSTEEL     668.25              -7.48           89.22          574.61   
28   KOTAKBANK   2,002.00              -3.69           26.48          522.52   
29          LT   1,820.00              -3.72           27.97          502.81   
30         M&M        885              -4.06           39.34          338.08   
31      MARUTI   7,520.00              -5.58           11.55          840.81   
32   NESTLEIND  19,148.85               0.38            0.56          108.61   
33        NTPC      133.2              -4.84          133.24          173.94   
34        ONGC     152.25              -4.74          231.36          344.33   
35   POWERGRID     204.05              -0.86           96.11          195.09   
36    RELIANCE   2,467.80              -3.52           72.75        1,770.19   
37     SBILIFE   1,154.00              -2.47           23.16          262.43   
38        SBIN     486.25              -4.19          263.06        1,249.55   
39    SHREECEM  26,450.00              -2.89            0.30           76.94   
40   SUNPHARMA        775              -2.00           54.33          424.05   
41  TATACONSUM      800.2              -4.69           26.17          203.32   
42  TATAMOTORS        486              -6.77          517.88        2,430.36   
43   TATASTEEL   1,157.90              -5.40          106.46        1,200.79   
44         TCS   3,425.00              -0.19           19.41          670.58   
45       TECHM   1,544.00              -2.59           15.22          232.97   
46       TITAN   2,377.80              -4.37           12.89          298.54   
47  ULTRACEMCO   7,550.00              -2.76            2.66          198.32   
48         UPL        726              -3.27           24.82          176.35   
49       W

In [16]:
df.fillna('_')

Name       Open  Percentage Change  Volumein Lakhs Turnover (crs.)  \
0   ADANIPORTS        750              -6.22           72.20          532.63   
1   ASIANPAINT   3,101.00              -0.20           10.29          322.53   
2     AXISBANK        669              -2.78          102.53             684   
3   BAJAJ-AUTO   3,370.00              -1.67            3.42          114.59   
4   BAJAJFINSV  17,200.00              -3.94            3.42          576.79   
5   BAJFINANCE   7,021.00              -4.85           16.89        1,161.63   
6   BHARTIARTL        763              -3.83          111.43          830.06   
7         BPCL     397.15              -5.67          100.23          383.54   
8    BRITANNIA   3,560.00              -0.19            3.73          133.23   
9        CIPLA        892               7.23          144.59        1,380.90   
10   COALINDIA     157.75              -1.67          118.30           185.5   
11    DIVISLAB   4,770.00               2.92           15.71          775.37   
12     DRREDDY   4,580.00               3.45           10.72          508.97   
13   EICHERMOT   2,495.00              -3.16            5.55          136.56   
14      GRASIM   1,757.30              -4.58            7.48          127.84   
15     HCLTECH   1,120.00              -1.17           22.07          246.06   
16        HDFC   2,820.35              -4.28           33.53          927.88   
17    HDFCBANK   1,500.00              -2.39           93.12        1,394.10   
18    HDFCLIFE        685              -2.77           22.37           151.4   
19  HEROMOTOCO   2,580.00              -2.62            6.85          174.04   
20    HINDALCO      441.8              -6.57          148.26          631.93   
21  HINDUNILVR   2,344.00              -0.35           24.51          572.85   
22   ICICIBANK        739              -4.07          189.88        1,385.86   
23  INDUSINDBK        951              -6.19           67.46          622.74   
24        INFY   1,702.55              -1.91           44.94          764.67   
25         IOC      125.6              -3.58           77.25           94.57   
26         ITC      228.9              -3.33          270.27          610.54   
27    JSWSTEEL     668.25              -7.48           89.22          574.61   
28   KOTAKBANK   2,002.00              -3.69           26.48          522.52   
29          LT   1,820.00              -3.72           27.97          502.81   
30         M&M        885              -4.06           39.34          338.08   
31      MARUTI   7,520.00              -5.58           11.55          840.81   
32   NESTLEIND  19,148.85               0.38            0.56          108.61   
33        NTPC      133.2              -4.84          133.24          173.94   
34        ONGC     152.25              -4.74          231.36          344.33   
35   POWERGRID     204.05              -0.86           96.11          195.09   
36    RELIANCE   2,467.80              -3.52           72.75        1,770.19   
37     SBILIFE   1,154.00              -2.47           23.16          262.43   
38        SBIN     486.25              -4.19          263.06        1,249.55   
39    SHREECEM  26,450.00              -2.89            0.30           76.94   
40   SUNPHARMA        775              -2.00           54.33          424.05   
41  TATACONSUM      800.2              -4.69           26.17          203.32   
42  TATAMOTORS        486              -6.77          517.88        2,430.36   
43   TATASTEEL   1,157.90              -5.40          106.46        1,200.79   
44         TCS   3,425.00              -0.19           19.41          670.58   
45       TECHM   1,544.00              -2.59           15.22          232.97   
46       TITAN   2,377.80              -4.37           12.89          298.54   
47  ULTRACEMCO   7,550.00              -2.76            2.66          198.32   
48         UPL        726              -3.27           24.82          176.35   
49       W

In [17]:
#df['Open'].fillna(df['Open'].median(),inplace=True)
df['Name'].fillna('Name',inplace=True)
#df['Fare'].fillna(df['Fare'].median(),inplace=True)

C:\Users\maury\AppData\Local\Temp\ipykernel_1592\588593484.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Name'].fillna('Name',inplace=True)


In [18]:
le=LabelEncoder()
df['Name']= le.fit_transform(df['Name'])
df['Open']= le.fit_transform(df['Open'])
df['Percentage Change']= le.fit_transform(df['Percentage Change'])
df['Volumein Lakhs']= le.fit_transform(df['Volumein Lakhs'])
df['Turnover (crs.)']= le.fit_transform(df['Turnover (crs.)'])
df['365 d % chng']= le.fit_transform(df['365 d % chng'])
df['30 d % chng']= le.fit_transform(df['30 d % chng'])
df.head()

Name  Open  Percentage Change  Volumein Lakhs  Turnover (crs.)  \
0     0    43                  3              30               34   
1     1    24                 42               8               26   
2     2    36                 28              37               42   
3     3    25                 38               3                8   
4     4    12                 18               3               37   

   365 d % chng  30 d % chng  
0            41           29  
1            29           46  
2            15            1  
3            12            7  
4            45           16

In [19]:
df['30 d % chng'].unique()


array([29, 46,  1,  7, 16,  4, 47,  6, 33, 48,  9, 38, 45, 23, 34, 28, 24,
       11, 35, 22,  3, 31,  5,  0, 42, 18, 26, 15,  8, 41, 30, 37, 43, 10,
       14, 49, 13, 32, 17, 20, 25, 27, 12,  2, 40, 36, 21, 44, 39, 19])

In [20]:
df['365 d % chng'].unique()

array([41, 29, 15, 12, 45, 28, 35,  2,  4, 22, 20, 27,  3,  1, 47, 24, 19,
       10,  5,  0, 44, 13, 33,  9, 31, 26, 16, 43,  8, 36, 17,  6, 14, 25,
       42,  7, 18, 23, 46, 11, 32, 30, 49, 48, 21, 39, 38, 34, 37, 40])

In [21]:
#ss = StandardScaler()
#df[['30 d % chng','365 d % chng']] = ss.fit_transform(df[['30 d % chng','365 d % chng']])
#df.head(10)

In [22]:
x= df[['Open','Percentage Change','Volumein Lakhs','Turnover (crs.)','365 d % chng','30 d % chng']]#feature 
y=df['Name'] 

In [23]:
x_train,x_test, y_train , y_test = train_test_split(x,y,test_size=0.2)

In [24]:
model= LogisticRegression()
model.fit(x_train,y_train)

c:\Users\maury\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
y_pred =model.predict(x_test)
print(y_pred)

[ 8  7 21 37 21 13 45 37 16  0]


In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [28]:
print(accuracy_score(y_test,y_pred))

0.0


In [29]:
print(confusion_matrix(y_test,y_pred))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [30]:
model_dt=DecisionTreeClassifier()
model_dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [31]:
model_rf = RandomForestClassifier()
model_rf.fit(x_train,y_train)

RandomForestClassifier()

In [32]:
with open(r'C:\Users\maury\OneDrive\Desktop\task3\Stock.pkl','wb') as f:
    pickle.dump(model,f)
